version: '3.4'
services:
  backend:
    build: .
    ports:
      - 8180:8180
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/ogarnizerAPI
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    depends_on:
      PostgreSQL:
        condition: service_healthy
  PostgreSQL:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ogarnizerAPI
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
networks:
  spring-boot-postgres: